<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="FacadeICadastroWSService" targetNamespace="http://impl.cadastro.kernel.sistema/" xmlns:ns1="http://prov.spec.cadastro.kernel.sistema/" xmlns:ns2="http://cxf.apache.org/bindings/xformat" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.cadastro.kernel.sistema/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="http://localhost:8080/MailServer/ws/iCadastroWS?wsdl=ICadastroWS.wsdl" namespace="http://prov.spec.cadastro.kernel.sistema/">
    </wsdl:import>
  <wsdl:binding name="FacadeICadastroWSServiceSoapBinding" type="ns1:ICadastroWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getUser">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getUser">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getUserResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="registerUser">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="registerUser">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="registerUserResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="deleteUser">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="deleteUser">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="deleteUserResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateUser">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="updateUser">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateUserResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="changePassword">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="changePassword">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="changePasswordResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FacadeICadastroWSService">
    <wsdl:port binding="tns:FacadeICadastroWSServiceSoapBinding" name="FacadeICadastroWSPort">
      <soap:address location="http://localhost:8080/MailServer/ws/iCadastroWS"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>